[project]
name = "llm-performance-review"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.6",
    "langchain-ollama>=0.2.2",
    "uvicorn>=0.34.0",
]
